# Generated by Django 4.2.4 on 2023-08-27 12:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="facebook",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="instagram",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="tiktok",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="website",
        ),
    ]
