# Generated by Django 4.2.4 on 2023-08-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="status",
            field=models.BooleanField(default=True),
        ),
    ]
