branch-defaults:
  master:
    environment: null
global:
  application_name: nodeme-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.11
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
