# Generated by Django 4.2.4 on 2023-08-27 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("linkedin", "LinkedIn"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("twitter", "Twitter"),
                            ("facebook", "Facebook"),
                            ("github", "GitHub"),
                            ("youtube", "YouTube"),
                            ("medium", "Medium"),
                            ("reddit", "Reddit"),
                            ("stackoverflow", "Stack Overflow"),
                            ("discord", "Discord"),
                            ("twitch", "Twitch"),
                            ("steam", "Steam"),
                            ("spotify", "Spotify"),
                            ("pinterest", "Pinterest"),
                            ("snapchat", "Snapchat"),
                            ("tumblr", "Tumblr"),
                            ("vimeo", "Vimeo"),
                            ("whatsapp", "WhatsApp"),
                            ("telegram", "Telegram"),
                            ("skype", "Skype"),
                            ("quora", "Quora"),
                            ("soundcloud", "SoundCloud"),
                            ("github_gist", "GitHub Gist"),
                            ("dribbble", "Dribbble"),
                            ("behance", "Behance"),
                            ("devto", "Dev.to"),
                            ("codepen", "CodePen"),
                            ("foursquare", "Foursquare"),
                            ("goodreads", "Goodreads"),
                            ("hackernews", "Hacker News"),
                            ("keybase", "Keybase"),
                            ("kaggle", "Kaggle"),
                            ("lastfm", "Last.fm"),
                            ("gitlab", "GitLab"),
                            ("bitbucket", "Bitbucket"),
                            ("mixcloud", "Mixcloud"),
                            ("producthunt", "Product Hunt"),
                            ("slideshare", "SlideShare"),
                            ("basecamp", "Basecamp"),
                            ("freecodecamp", "freeCodeCamp"),
                            ("wordpress", "WordPress"),
                            ("aboutme", "About.me"),
                            ("bandcamp", "Bandcamp"),
                        ],
                        max_length=255,
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="links",
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
