# Generated by Django 4.2.4 on 2023-08-27 12:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0001_initial"),
        ("links", "0002_rename_user_link_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="links", to="tags.tag"
            ),
        ),
    ]
