# Generated by Django 4.2.4 on 2023-11-23 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("links", "0002_customlink"),
    ]

    operations = [
        migrations.RemoveField(model_name="customlink", name="profile",),
        migrations.AddField(
            model_name="customlink",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="customlinks",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
